# -*- coding: utf-8 -*-
"""Runtime translation helpers for the integrated PileAnalysis desktop."""

from __future__ import annotations

from typing import Dict

from PySide6.QtWidgets import QMenu, QTableWidget, QTabWidget, QWidget

from language_manager import get_language


EN_TO_ZH: Dict[str, str] = {
    "PileAnalysis Launcher": "PileAnalysis 启动器",
    "PileAnalysis - Foundation Analysis": "PileAnalysis - 桩基分析程序",
    "PileAnalysis - M-Method ": "PileAnalysis - M 法",
    "PileAnalysis - M-Method": "PileAnalysis - M 法",
    "PileAnalysis - Nonlinear": "PileAnalysis - 非线性法",
    "Step 1: Select language. Step 2: Choose the analysis method.": "第 1 步：选择语言。第 2 步：选择分析方法。",
    "Selected language: English": "已选择语言：英文",
    "Selected language: 中文": "已选择语言：中文",
    "No language selected": "尚未选择语言",
    "Select the analysis method to launch.": "请选择要启动的分析方法。",
    "Open M-Method": "打开 M 法",
    "Open Nonlinear": "打开 非线性法",
    "English": "English",
    "中文": "中文",
    "Export(&E)": "导出(&E)",
    "Help(&H)": "帮助(&H)",
    "Tutorial(&T)": "教程(&T)",
    "Navigate": "切换",
    "Language": "语言",
    "Open Launcher": "打开启动器",
    "Open M-Method Program": "打开 M 法程序",
    "Open Nonlinear Program": "打开 非线性法程序",
    "About": "关于",
    "Ready": "准备就绪",
    "Preparation Complete": "准备就绪",
    "Running...": "计算中...",
    "Running Analysis": "正在计算",
    "Running Back Analysis": "正在进行反算",
    "Run Failed": "计算失败",
    "Calculation Failed": "计算失败",
    "Completed": "已完成",
    "Saved": "已保存",
    "Export": "导出",
    "Export Results": "导出结果",
    "Export Failed": "导出失败",
    "Exported": "导出完成",
    "Notice": "提示",
    "Warning": "警告",
    "Error": "错误",
    "Critical": "严重错误",
    "Import Failed": "导入失败",
    "Import Completed": "导入完成",
    "Export Completed": "导出完成",
    "Invalid Mode": "模式无效",
    "Case Selection": "工况选择",
    "Existing Case": "现有工况",
    "New Case": "新建工况",
    "Analysis Scope Selection": "分析范围选择",
    "Single Pile Analysis": "单桩分析",
    "Group Pile Analysis": "群桩分析",
    "Back to Case Selection": "返回工况选择",
    "Import Existing Case (.dat)": "导入现有工况 (.dat)",
    "View and Edit": "查看并编辑",
    "Run Directly": "直接计算",
    "Single Pile Mode Selection": "单桩模式选择",
    "Back to Scope Selection": "返回范围选择",
    "Axial Analysis": "轴向分析",
    "Lateral Analysis": "横向分析",
    "Combined Analysis": "组合分析",
    "Result Output": "计算结果输出区",
    "Summary": "结果摘要",
    "Data Table": "数据表",
    "Raw Output": "原始输出",
    "Result summary will be displayed here...": "计算结果摘要将显示在此。",
    "Result summary will be displayed here.": "计算结果摘要将显示在此。",
    "Quick Start Guide": "快速上手指南",
    "Quick Start": "快速上手",
    "Save Case": "保存工况",
    "Save and Export": "保存并导出",
    "Run": "开始计算",
    "Parameter Reference": "参数参考",
    "Export Summary": "导出摘要",
    "Export Data Table CSV": "导出数据表 CSV",
    "Export Response Charts": "导出响应图",
    "Export All Results": "导出全部结果",
    "Export Plots Only": "仅导出图形",
    "Export Text Results Only": "仅导出文本结果",
    "Export Stiffness Matrix CSV": "导出刚度矩阵 CSV",
    "Export Summary CSV": "导出摘要 CSV",
    "Analysis Schematic": "计算原理示意图",
    "Plot Area": "图形绘制区",
    "3D Layout": "立体布置图",
    "Plan Layout": "平面布置图",
    "Pile Response": "桩身响应",
    "Pile Response Figure": "桩身响应图",
    "Pile Response图": "桩身响应",
    "Live": "实时",
    "Response": "响应",
    "Basic Parameters": "基本参数",
    "Pile Material Parameters": "桩身材料参数",
    "Above-Ground Segment (Free Segment) - Optional": "地上段（自由段）- 可选",
    "Embedded Segment (Soil Parameters) - Required": "地下段（土层参数）- 必填",
    "Pile Tip Parameters": "桩端参数",
    "Load Count": "荷载数量",
    "Cap-Center Load (Forward Mode)": "承台中心荷载（正算模式）",
    "Cap-Center Displacement (Back Analysis Mode)": "承台中心位移（反算模式）",
    "Multiple Load Input": "多工况荷载输入",
    "Pile Type Management": "桩类型管理",
    "Currently Editing:": "当前编辑：",
    "Please click [New] to create a pile type first": "请先点击 [新建] 创建桩类型",
    "Target Pile No.": "目标桩号",
    "Target Pile No.:": "目标桩号：",
    "Pile Layout and Type Assignment": "桩位布置与类型分配",
    "Simulated Pile Settings": "模拟桩设置",
    "Stiffness Input Type:": "刚度输入类型：",
    "Pile Definition": "桩定义",
    "Cap Definition": "承台定义",
    "Pile Arrangement": "桩基布置",
    "Pile Layout": "桩位布置",
    "Load Input": "荷载输入",
    "Batch Add Pile Coordinates": "批量添加桩坐标",
    "Current Material:": "当前材料：",
    "Current Type:": "当前类型：",
    "New": "新建",
    "Delete": "删除",
    "Rename": "重命名",
    "Pick Layer Color": "选择土层颜色",
    "Add Layer": "添加土层",
    "Delete Layer": "删除土层",
    "Add Pile": "添加桩",
    "Delete Pile": "删除桩",
    "Mesh control": "网格控制",
    "Enable advanced mesh settings": "启用高级网格设置",
    "Mesh type:": "网格类型：",
    "Element number": "单元数量",
    "Element length": "单元长度",
    "User define": "自定义",
    "Add Segment": "添加分段",
    "Delete Segment": "删除分段",
    "Overview": "总览",
    "Displacement": "位移",
    "Displacement X": "X 向位移",
    "Displacement Y": "Y 向位移",
    "Displacement Z": "Z 向位移",
    "Axial Force": "轴力",
    "Shear X'": "剪力 X'",
    "Shear Y'": "剪力 Y'",
    "Moment X'": "弯矩 X'",
    "Moment Y'": "弯矩 Y'",
    "Beam Axial Force": "梁轴力",
    "Bending Moment": "弯矩",
    "PILE Manual Example Review": "PILE 手册算例查看",
    "Reference Figure": "参考图",
    "Example Analysis": "算例分析",
    "DAT Input File": "DAT 输入文件",
    "Example Notes and Commentary": "算例说明与注释",
    "PILE Manual Example Table": "PILE 手册算例表",
    "PILE Manual": "PILE 手册",
    "DAT File Analysis and Notes": "DAT 文件分析与说明",
    "Authors:": "作者：",
    "Authors: Can Wang, Junjun Guo": "作者：Can Wang, Junjun Guo",
    "Contact:": "联系方式：",
    "Contact: 24231238@bjtu.edu.cn / jjguo2@bjtu.edu.cn": "联系方式：24231238@bjtu.edu.cn / jjguo2@bjtu.edu.cn",
    "Version: 3.0": "版本：3.0",
        "Project Repository": "项目仓库",
        "Update": "更新",
    "X:": "X：",
    "Y:": "Y：",
    "Please enter a value, unit: ": "请输入数值，单位：",
    "The 3D pile-group layout will be displayed after the calculation is complete": "计算完成后将显示桩基三维布置图",
    "The 3D pile layout will be displayed after the calculation is complete": "计算完成后将显示桩基三维布置图",
    "Completed后将显示桩基三维布置图": "计算完成后将显示桩基三维布置图",
    "Response curves will be displayed after the calculation is complete": "计算完成后将显示响应曲线",
    "Completed后将显示响应曲线": "计算完成后将显示响应曲线",
    "-> Please select a case type": "↑ 请选择工况类型",
    "-> Please select an analysis scope": "↑ 请选择分析范围",
    "-> Please select a single pile mode": "↑ 请选择单桩模式",
    "-> Please import a case file first": "↑ 请先导入工况文件",
    "Soil Material": "土体材料",
    "Soil Layers": "土层信息",
    "Soil m Value": "土层 m 值",
    "Rock c0 Value": "岩层 c0 值",
    "Internal Friction Angle β": "内摩擦角 β",
    "Internal Friction Angle 蠁": "内摩擦角 β",
    "Concrete Parameters": "混凝土参数",
    "KSU Notes": "KSU 说明",
    "PileAnalysis Parameter Reference": "PileAnalysis 参数参考",
    "No pile layout data is available for plotting": "当前没有可用于绘图的桩位布置数据",
    "Tip": "提示",
}


EN_TO_ZH.update(
    {
        "Group Analysis": "群桩分析",
        "Group Pile Analysis Summary": "群桩分析结果摘要",
        "Soil Material Management": "土材料管理",
        "Material Parameters": "材料参数",
        "Elastic Section Parameters": "弹性截面参数",
        "Pile Geometry": "桩几何参数",
        "Analysis diagram placeholder": "分析示意图将在此显示",
        "Add Case": "添加工况",
        "Delete Case": "删除工况",
        "Add Load Case": "添加荷载工况",
        "Delete Load Case": "删除荷载工况",
        "Change File": "更换文件",
        "Parameter Error": "参数错误",
        "Computing...": "计算中...",
        "Initializing...": "初始化中...",
        "Preparing calculation...": "正在准备计算...",
        "Rendering results...": "正在渲染结果...",
        "Result rendering failed:": "结果渲染失败：",
        "Run analysis to generate response plots.": "运行分析后将在此生成响应曲线。",
        "Run group analysis to generate response plots.": "运行群桩分析后将在此生成响应曲线。",
        "Click a tab to load the chart.": "点击标签加载图表。",
        "Loading chart…": "图表加载中…",
        "matplotlib is unavailable in this environment.": "当前环境缺少 matplotlib，无法绘图。",
        "No plot data is available for this response quantity.": "当前响应量没有可绘制的数据。",
        "Tip: Press Enter to jump between depth cells.": "提示：按 Enter 可在深度单元格间快速跳转。",
        "Tip: Press Enter to jump between coordinate cells.": "提示：按 Enter 可在坐标单元格间快速跳转。",
        "Axial": "轴向",
        "Lateral": "横向",
        "Section Model": "截面模型",
        "Elastic": "弹性",
        "Nonlinear Fiber": "非线性纤维",
        "Comparison": "对比",
        "Fiber": "纤维",
        "Fiber Section Definition": "纤维截面定义",
        "Pile Section Layout": "桩身截面布置",
        "Section:": "截面：",
        "Import H5": "导入 H5",
        "Case Name": "工况名称",
        "Concrete Material": "混凝土材料",
        "Rebar Material": "钢筋材料",
        "Stirrup Type": "箍筋类型",
        "Stirrup Diameter (m)": "箍筋直径 (m)",
        "Stirrup Space (m)": "箍筋间距 (m)",
        "Stirrup Yield Strength (MPa)": "箍筋屈服强度 (MPa)",
        "Rebar Space (m)": "纵筋间距 (m)",
        "Stirrup Ratio Y": "Y 向箍筋率",
        "Stirrup Ratio Z": "Z 向箍筋率",
        "Fiber Count": "纤维数",
        "Rebar Groups": "钢筋组数",
        "Area (m^2)": "面积 (m^2)",
        "Rebar Area (m^2)": "钢筋面积 (m^2)",
        "Rebar Ratio": "配筋率",
        "Group": "组别",
        "Total Area (m^2)": "总面积 (m^2)",
        "Section Preview": "截面预览",
        "Mesh": "网格",
        "Fiber Points": "纤维点",
        "No section loaded": "尚未加载截面",
        "Define pile sections by top/bottom depth and imported fiber section.": "请通过顶/底深度和已导入纤维截面定义桩身分段。",
        "Define fiber-section segments from 0.0 m to ": "请定义 0.0 m 到 ",
        "Custom mesh table is empty.": "自定义网格表为空。",
        "Custom mesh must start at 0.0 m.": "自定义网格必须从 0.0 m 开始。",
        "Custom mesh must end exactly at the pile length ": "自定义网格的末端必须与桩长一致：",
        "Custom mesh segment ": "自定义网格分段 ",
        " is not continuous with the previous segment.": " 与上一分段不连续。",
        " has an invalid start/end range.": " 的起止范围无效。",
        " must have at least 1 element.": " 至少需要 1 个单元。",
        " must fill both top length and bottom length, or leave both blank.": " 的顶部长度和底部长度必须同时填写，或同时留空。",
        " top length must be positive.": " 的顶部长度必须为正。",
        " bottom length must be positive.": " 的底部长度必须为正。",
        "For user-defined mesh, the first start must be 0.0 m and the final end must equal ": "自定义网格中，首段起点必须为 0.0 m，末段终点必须等于",
        "the pile length ": "桩长 ",
        ". Top/bottom lengths are optional and define linear grading.": "。顶部/底部长度为可选项，用于定义线性渐变。",
        "Soil Material Help": "土材料帮助",
        "Material Help": "材料帮助",
        "Show help": "显示帮助",
        "Use the Help menu to open the soil material manual.": "请通过“帮助”菜单打开土材料说明手册。",
        "Applicable use:": "适用范围：",
        "Panel Parameters": "面板参数",
        "No help text has been prepared for this item yet.": "该项帮助内容尚未准备。",
        "No help text has been prepared yet for ": "尚未为以下对象准备帮助内容：",
        "Current model": "当前模型",
        "How it is used": "用途说明",
        "Reference notes": "参考说明",
        "Pile": "桩",
        "Case imported. Choose View and Edit or Run Directly": "工况已导入，请选择“查看并编辑”或“直接运行”",
        "Please select single or group analysis, or import an existing case directly": "请选择单桩或群桩分析，或直接导入已有工况",
        "Please select an analysis scope to start a blank case": "请选择分析范围以开始新建空白工况",
        "Please select single or group analysis, then import a case file": "请选择单桩或群桩分析，然后导入工况文件",
        "Import a single-pile case file; mode will be detected automatically": "导入单桩工况文件后，程序将自动识别分析模式",
        "Start with pile types, pile layout, soil layers, and one load case": "请先设置桩型、桩位布置、土层以及至少一个荷载工况",
        "Import a group-pile case file; detailed tabs will stay collapsed": "导入群桩工况文件后，详细参数页将保持折叠状态",
        "Start with pile geometry, at least one material/layer, and one load case": "请先设置桩几何、至少一个材料/土层以及一个荷载工况",
        "Help(&H)": "帮助(&H)",
        "Examples(&T)": "教程(&T)",
        "Update": "更新",
        "Authors: Wang Can, Guo Junjun": "作者：汪灿，郭军军",
        "Authors: Can Wang, Junjun Guo": "作者：汪灿，郭军军",
        "Contact: 24231238@bjtu.edu.cn / jjguo2@bjtu.edu.cn": "联系方式：24231238@bjtu.edu.cn / jjguo2@bjtu.edu.cn",
        "Version: 3.0": "版本：3.0",
        "Axial Tutorial": "轴向算例",
        "Lateral Tutorial": "横向算例",
        "Combined Tutorial": "组合算例",
        "Group Tutorial": "群桩算例",
        "Soil model": "土模型",
        "Layer color": "土层颜色",
        "Top z (-m)": "层顶 z (-m)",
        "Bottom z (-m)": "层底 z (-m)",
        "Pile shape": "桩形",
        "Diameter (m)": "直径 (m)",
        "Thickness (m, pipe)": "壁厚 (m，管桩)",
        "Concrete material": "混凝土材料",
        "Elastic modulus E (kPa)": "弹性模量 E (kPa)",
        "Type": "类型",
        "Value": "数值",
        "Depth (-m)": "深度 (-m)",
        "Axial Force N (kN)": "轴向力 N (kN)",
        "Top (m)": "顶部深度 (m)",
        "Bottom (m)": "底部深度 (m)",
        "Section": "截面",
        "Index": "序号",
        "Depth (m)": "深度 (m)",
        "Disp (mm)": "位移 (mm)",
        "Rotation (rad)": "转角 (rad)",
        "Soil Reaction (kN)": "土反力 (kN)",
        "Soil Reaction per m (kN/m)": "单位长度土反力 (kN/m)",
        "Soil Stiffness (kN/m^2)": "土刚度 (kN/m^2)",
        "Ele Depth (m)": "单元深度 (m)",
        "Moment (kN*m)": "弯矩 (kN*m)",
        "Shear (kN)": "剪力 (kN)",
        "Disp X (mm)": "X 向位移 (mm)",
        "Disp Y (mm)": "Y 向位移 (mm)",
        "Head Disp X (mm)": "桩头 X 位移 (mm)",
        "Head Disp Y (mm)": "桩头 Y 位移 (mm)",
        "Head Disp Z (mm, +up/-down)": "桩头 Z 位移 (mm, +up/-down)",
        "Max |Axial| (kN)": "最大|轴力| (kN)",
        "Max |Shear| (kN)": "最大|剪力| (kN)",
        "Max |Moment| (kN*m)": "最大|弯矩| (kN*m)",
        "Node": "节点",
        "Section Depth (m)": "截面深度 (m)",
        "Unknown": "未知",
        "Loaded: ": "已加载：",
        "Sample case not found:": "未找到示例工况：",
        "Unsupported case mode: ": "不支持的工况模式：",
        "Save Failed": "保存失败",
        "Case saved:\n": "工况已保存：\n",
        "Summary exported:\n": "摘要已导出：\n",
        "CSV exported:\n": "CSV 已导出：\n",
        "Charts exported to:\n": "图表已导出至：\n",
        "Spring parameters exported:\n": "弹簧参数已导出：\n",
        "No completed analysis is available to export spring parameters.": "当前没有可用于导出弹簧参数的已完成分析结果。",
        "Import Existing Case": "导入已有工况",
        "DAT Files (*.dat);;All Files (*)": "DAT 文件 (*.dat);;所有文件 (*)",
        "Text Files (*.txt);;All Files (*)": "文本文件 (*.txt);;所有文件 (*)",
        "CSV Files (*.csv);;All Files (*)": "CSV 文件 (*.csv);;所有文件 (*)",
        "Excel Files (*.xlsx);;All Files (*)": "Excel 文件 (*.xlsx);;所有文件 (*)",
        "Save Case": "保存工况",
        "Export Summary": "导出摘要",
        "Export Data Table CSV": "导出数据表 CSV",
        "Export Response Charts": "导出响应曲线图",
        "Export Spring Parameters": "导出弹簧参数",
        "About PileAnalysis": "关于 PileAnalysis",
        "Nonlinear pile foundation analysis environment.": "非线性桩基础分析环境。",
        "Supports axial, lateral, combined, and group pile analysis.": "支持轴向、横向、组合以及群桩分析。",
        "Authors:": "作者：",
        "Version:": "版本：",
        "Collecting elastic parameters...": "正在收集弹性参数...",
        "Running elastic solver...": "正在进行弹性求解...",
        "Collecting fiber parameters...": "正在收集纤维参数...",
        "Running fiber solver...": "正在进行纤维求解...",
        "Collecting parameters...": "正在收集参数...",
        "Running solver...": "正在求解...",
        "Preparing results...": "正在整理结果...",
        "Elastic": "弹性",
        "Fiber": "纤维",
        "Metric": "指标",
        "Top displacement Z (mm)": "桩顶 Z 位移 (mm)",
        "Total skin friction Z (kN)": "总侧摩阻 Z (kN)",
        "End bearing Z (kN)": "端阻力 Z (kN)",
        "Total skin friction accumulated (kN)": "总侧摩阻累计值 (kN)",
        "Top displacement (mm)": "桩顶位移 (mm)",
        "Max moment (kN*m)": "最大弯矩 (kN*m)",
        "Max moment depth (m)": "最大弯矩深度 (m)",
        "Head displacement X (mm)": "桩头 X 位移 (mm)",
        "Max |axial force| (kN)": "最大|轴力| (kN)",
        "Max |shear| (kN)": "最大|剪力| (kN)",
        "Max |moment| (kN*m)": "最大|弯矩| (kN*m)",
        "Disp Z (mm, +up/-down)": "Z 位移 (mm, +up/-down)",
        "Axial Force (kN)": "轴力 (kN)",
        "Skin Friction Z (kN)": "侧摩阻 Z (kN)",
        "Ult Skin Z (kN)": "极限侧摩阻 Z (kN)",
        "Soil Stiffness (kN/m)": "土刚度 (kN/m)",
        "Axial Force Z (kN, +up/-down)": "轴力 Z (kN, +up/-down)",
        "Pile ": "桩 ",
        "Pile top z (m)": "桩顶 z (m)",
        "Pile bottom z (m)": "桩底 z (m)",
        "Length (m)": "长度 (m)",
        "Pile geometry": "桩几何",
        "Cap length X (m)": "承台 X 向尺寸 (m)",
        "Cap length Y (m)": "承台 Y 向尺寸 (m)",
        "Cap height (m)": "承台高度 (m)",
        "Cap center z (m)": "承台中心 z (m)",
        "Cap top z (m)": "承台顶面 z (m)",
        "Cap bottom z (m)": "承台底面 z (m)",
        "X (m)": "X 坐标 (m)",
        "Y (m)": "Y 坐标 (m)",
        "Pile Type": "桩类型",
        "Connectivity": "连接方式",
        "At least one soil material is required.": "至少需要一个土材料。",
        "At least one soil layer is required.": "至少需要一个土层。",
        "First layer top depth is fixed at 0.0 m.": "首层顶面深度固定为 0.0 m。",
        "First layer top depth must start at 0.0 m.": "首层顶面深度必须从 0.0 m 开始。",
        "Soil layers must be sorted and non-overlapping.": "土层必须按深度顺序排列且不能重叠。",
        "Invalid pipe section geometry.": "管桩截面几何参数无效。",
        "Layer row ": "第 ",
        " is incomplete.": " 层数据未填写完整。",
        " has invalid depth value.": " 层深度数值无效。",
        ": bottom depth must be larger than top depth.": " 层底深度必须大于层顶深度。",
        ": bottom depth must be smaller than top depth.": " 层底深度必须小于层顶深度。",
        ": invalid material selection.": " 层材料选择无效。",
        "Pile row ": "第 ",
        " mesh setting is invalid for pile length ": " 根桩的网格设置对桩长 ",
        " m: ": " m 无效：",
        "At least one material is required.": "至少需要一个材料。",
        "Loaded:": "已加载：",
        "Soil Layer Column": "土层柱状图",
        "3D Pile and Layered Soil": "三维桩土示意图",
        "Depth From Ground Line (m)": "距地表深度 (m)",
    }
)

ZH_TO_EN: Dict[str, str] = {value: key for key, value in EN_TO_ZH.items()}
ZH_TO_EN.update(
    {
        "导出(E)": "Export(&E)",
        "导出（E）": "Export(&E)",
        "帮助(H)": "Help(&H)",
        "帮助（H）": "Help(&H)",
        "教程(T)": "Tutorial(&T)",
        "教程（T）": "Tutorial(&T)",
        "PileAnalysis - 桩基分析程序 ": "PileAnalysis - M-Method",
        "PileAnalysis - 桩基分析程序": "PileAnalysis - M-Method",
        "计算原理示意图": "Analysis Schematic",
        "桩基计算原理示意图": "Analysis Schematic",
        "快速上手指南": "Quick Start Guide",
        "工况选择": "Case Selection",
        "现有工况": "Existing Case",
        "新建工况": "New Case",
        "立体布置图": "3D Layout",
        "平面布置图": "Plan Layout",
        "桩身响应": "Pile Response",
        "桩身响应图": "Pile Response",
        "位移": "Displacement",
        "轴力": "Axial Force",
        "弯矩": "Bending Moment",
        "结果摘要": "Summary",
        "原始输出": "Raw Output",
        "计算结果输出区": "Result Output",
        "计算结果摘要将显示在此。": "Result summary will be displayed here...",
        "计算结果摘要将显示在此...": "Result summary will be displayed here...",
        "计算完成后将显示桩基三维布置图": "The 3D pile-group layout will be displayed after the calculation is complete",
        "计算完成后将显示响应曲线": "Response curves will be displayed after the calculation is complete",
        "↑ 请选择工况类型": "-> Please select a case type",
        "↑ 请选择分析范围": "-> Please select an analysis scope",
        "↑ 请选择单桩模式": "-> Please select a single pile mode",
        "↑ 请先导入工况文件": "-> Please import a case file first",
    }
)


def translate_text(text: str | None, language: str | None = None) -> str | None:
    if text is None:
        return None
    language = language or get_language()
    mapping = EN_TO_ZH if language == "zh" else ZH_TO_EN
    translated = text
    for src in sorted(mapping.keys(), key=len, reverse=True):
        translated = translated.replace(src, mapping[src])
    return translated


def translate_widget_tree(root: QWidget, language: str | None = None) -> None:
    language = language or get_language()
    _translate_widget(root, language)
    for child in root.findChildren(QWidget):
        if child is not root:
            _translate_widget(child, language)


def _translate_widget(widget: QWidget, language: str) -> None:
    if hasattr(widget, "text") and hasattr(widget, "setText"):
        try:
            widget.setText(translate_text(widget.text(), language))
        except Exception:
            pass
    if hasattr(widget, "title") and hasattr(widget, "setTitle"):
        try:
            widget.setTitle(translate_text(widget.title(), language))
        except Exception:
            pass
    if hasattr(widget, "windowTitle") and hasattr(widget, "setWindowTitle"):
        try:
            widget.setWindowTitle(translate_text(widget.windowTitle(), language))
        except Exception:
            pass
    if hasattr(widget, "toolTip") and hasattr(widget, "setToolTip"):
        try:
            widget.setToolTip(translate_text(widget.toolTip(), language))
        except Exception:
            pass
    if hasattr(widget, "placeholderText") and hasattr(widget, "setPlaceholderText"):
        try:
            widget.setPlaceholderText(translate_text(widget.placeholderText(), language))
        except Exception:
            pass
    if isinstance(widget, QTabWidget):
        for i in range(widget.count()):
            widget.setTabText(i, translate_text(widget.tabText(i), language))
    if isinstance(widget, QTableWidget):
        for i in range(widget.columnCount()):
            item = widget.horizontalHeaderItem(i)
            if item is not None:
                item.setText(translate_text(item.text(), language))
        for i in range(widget.rowCount()):
            item = widget.verticalHeaderItem(i)
            if item is not None:
                item.setText(translate_text(item.text(), language))


def translate_menu_bar(window: QWidget, language: str | None = None) -> None:
    language = language or get_language()
    menubar = getattr(window, "menuBar", lambda: None)()
    if menubar is None:
        return
    for action in menubar.actions():
        action.setText(translate_text(action.text(), language))
        if action.menu() is not None:
            _translate_menu(action.menu(), language)


def _translate_menu(menu: QMenu, language: str) -> None:
    menu.setTitle(translate_text(menu.title(), language))
    for action in menu.actions():
        action.setText(translate_text(action.text(), language))
        if action.menu() is not None:
            _translate_menu(action.menu(), language)


EN_TO_ZH.update(
    {
        "Quick Start Guide": "快速开始指南",
        "1. Select case type (existing/new)": "1. 选择工况类型（已有/新建）",
        "2. Select analysis scope (single/group)": "2. 选择分析范围（单桩/群桩）",
        "3. For single pile, select axial / lateral / combined mode": "3. 单桩分析请选择轴向 / 横向 / 组合模式",
        "4. Fill parameters and click [Run]": "4. 填写参数后点击【开始计算】",
        "4. Fill parameters and click [开始计算]": "4. 填写参数后点击【开始计算】",
        "Soil Layer Column": "土层柱状图",
        "Depth From Ground Line (m)": "距地表深度 (m)",
        "3D Pile and Layered Soil": "三维桩土示意图",
        "3D Cap and Pile Group": "三维承台与群桩示意图",
        "Material Parameters": "材料参数",
        "Undrained Shear Strength (kPa)": "不排水抗剪强度 (kPa)",
        "Remolded Shear Strength (kPa)": "重塑抗剪强度 (kPa)",
        "Friction Angle (deg)": "内摩擦角 (deg)",
        "Strain Factor": "应变系数",
        "Ks (kN/m^3)": "Ks (kN/m^3)",
        "Initial Modulus of Subgrade Reaction (kN/m^3)": "地基反力系数初值 (kN/m^3)",
        "Uniaxial Compressive Strength (kPa)": "单轴抗压强度 (kPa)",
        "Reaction Modulus of Rock (kPa)": "岩体反力模量 (kPa)",
        "Rock Quality Designation (RQD) (%)": "岩石质量指标 RQD (%)",
        "Constant Krm": "常数 Krm",
        "Coefficient of Lateral Earth Pressure": "侧向土压力系数",
        "Bearing Capacity Factor": "承载力系数",
        "Unit Weight (kN/m^3)": "重度 (kN/m^3)",
        "Maximum Unit Skin Friction (kPa)": "极限单位侧摩阻力 (kPa)",
        "Maximum Unit End Bearing Resistance (kPa)": "极限单位端阻力 (kPa)",
        "Ultimate Shear Resistance (kPa)": "极限剪切阻力 (kPa)",
        "Ultimate End Bearing Resistance (kPa)": "极限端承阻力 (kPa)",
        "API Method for Sand": "API 砂土方法",
        "Soft Clay Soil": "软黏土",
        "Submerged Stiff Clay": "浸水硬黏土",
        "Dry Stiff Clay": "干硬黏土",
        "Modified Stiff Clay without Free Water": "无自由水修正硬黏土",
        "Weak Rock": "软弱岩层",
    }
)

ZH_TO_EN.update(
    {
        "快速开始指南": "Quick Start Guide",
        "1. 选择工况类型（已有/新建）": "1. Select case type (existing/new)",
        "2. 选择分析范围（单桩/群桩）": "2. Select analysis scope (single/group)",
        "3. 单桩分析请选择轴向 / 横向 / 组合模式": "3. For single pile, select axial / lateral / combined mode",
        "4. 填写参数后点击【开始计算】": "4. Fill parameters and click [Run]",
        "土层柱状图": "Soil Layer Column",
        "距地表深度 (m)": "Depth From Ground Line (m)",
        "三维桩土示意图": "3D Pile and Layered Soil",
        "三维承台与群桩示意图": "3D Cap and Pile Group",
        "材料参数": "Material Parameters",
        "不排水抗剪强度 (kPa)": "Undrained Shear Strength (kPa)",
        "重塑抗剪强度 (kPa)": "Remolded Shear Strength (kPa)",
        "内摩擦角 (deg)": "Friction Angle (deg)",
        "应变系数": "Strain Factor",
        "Ks (kN/m^3)": "Ks (kN/m^3)",
        "地基反力系数初值 (kN/m^3)": "Initial Modulus of Subgrade Reaction (kN/m^3)",
        "单轴抗压强度 (kPa)": "Uniaxial Compressive Strength (kPa)",
        "岩体反力模量 (kPa)": "Reaction Modulus of Rock (kPa)",
        "岩石质量指标 RQD (%)": "Rock Quality Designation (RQD) (%)",
        "常数 Krm": "Constant Krm",
        "侧向土压力系数": "Coefficient of Lateral Earth Pressure",
        "承载力系数": "Bearing Capacity Factor",
        "重度 (kN/m^3)": "Unit Weight (kN/m^3)",
        "极限单位侧摩阻力 (kPa)": "Maximum Unit Skin Friction (kPa)",
        "极限单位端阻力 (kPa)": "Maximum Unit End Bearing Resistance (kPa)",
        "极限剪切阻力 (kPa)": "Ultimate Shear Resistance (kPa)",
        "极限端承阻力 (kPa)": "Ultimate End Bearing Resistance (kPa)",
        "API 砂土方法": "API Method for Sand",
        "软黏土": "Soft Clay Soil",
        "浸水硬黏土": "Submerged Stiff Clay",
        "干硬黏土": "Dry Stiff Clay",
        "无自由水修正硬黏土": "Modified Stiff Clay without Free Water",
        "软弱岩层": "Weak Rock",
    }
)


EN_TO_ZH.update(
    {
        "Depth From Pile Head (m)": "距桩顶深度 (m)",
        "Displacement X (mm)": "X 向位移 (mm)",
        "Displacement Y (mm)": "Y 向位移 (mm)",
        "Displacement Z (mm, +up/-down)": "Z 向位移 (mm, +上/-下)",
        "Rotation Y (rad)": "Y 向转角 (rad)",
        "Beam Shear Force X' (kN)": "梁单元剪力 X' (kN)",
        "Beam Moment X'Z' (kN*m)": "梁单元弯矩 X'Z' (kN*m)",
        "Beam Shear X' (kN)": "梁单元剪力 X' (kN)",
        "Beam Shear Y' (kN)": "梁单元剪力 Y' (kN)",
        "Beam Moment Y'Z' (kN*m)": "梁单元弯矩 Y'Z' (kN*m)",
        "Soil Reaction Force X' (kN/m)": "土反力 X' (kN/m)",
        "Soil Stiffness X' (kN/m^2)": "土刚度 X' (kN/m^2)",
        "Disp X": "位移 X",
        "Disp Y": "位移 Y",
        "Disp Z": "位移 Z",
        "Rot Y": "转角 Y",
        "Soil Rxn": "土反力",
        "Soil K": "土刚度",
        "Loading chart...": "图表加载中...",
        "Click a tab to load the chart.": "点击标签以加载图表。",
    }
)

ZH_TO_EN.update(
    {
        "距桩顶深度 (m)": "Depth From Pile Head (m)",
        "X 向位移 (mm)": "Displacement X (mm)",
        "Y 向位移 (mm)": "Displacement Y (mm)",
        "Z 向位移 (mm, +上/-下)": "Displacement Z (mm, +up/-down)",
        "Y 向转角 (rad)": "Rotation Y (rad)",
        "梁单元剪力 X' (kN)": "Beam Shear Force X' (kN)",
        "梁单元弯矩 X'Z' (kN*m)": "Beam Moment X'Z' (kN*m)",
        "梁单元剪力 Y' (kN)": "Beam Shear Y' (kN)",
        "梁单元弯矩 Y'Z' (kN*m)": "Beam Moment Y'Z' (kN*m)",
        "土反力 X' (kN/m)": "Soil Reaction Force X' (kN/m)",
        "土刚度 X' (kN/m^2)": "Soil Stiffness X' (kN/m^2)",
        "位移 X": "Disp X",
        "位移 Y": "Disp Y",
        "位移 Z": "Disp Z",
        "转角 Y": "Rot Y",
        "土反力": "Soil Rxn",
        "土刚度": "Soil K",
        "图表加载中...": "Loading chart...",
        "点击标签以加载图表。": "Click a tab to load the chart.",
    }
)
